--List the most popular genre among the groups which are associated with at least 3 genres. 

SELECT GNAME
FROM (
SELECT G.NAME AS GNAME
FROM DUMMY_GENRE G, DUMMY_ARTIST_GENRE AG
WHERE G.ID_GENRE=AG.ID_GENRE AND AG.ID_ARTIST IN(
SELECT A.ID_ARTIST
FROM DUMMY_ARTIST A, DUMMY_ARTIST_GENRE AG, DUMMY_ARTIST_GENRE AG2, DUMMY_ARTIST_GENRE AG3
WHERE A.TYPE = 'Group' AND AG.ID_ARTIST = A.ID_ARTIST AND  AG2.ID_ARTIST = A.ID_ARTIST AND  AG3.ID_ARTIST = A.ID_ARTIST 
AND AG.ID_GENRE <> AG2.ID_GENRE AND AG2.ID_GENRE <> AG3.ID_GENRE AND AG3.ID_GENRE <> AG.ID_GENRE)
GROUP BY G.ID_GENRE, G.NAME
ORDER BY COUNT(DISTINCT AG.ID_ARTIST) DESC

) WHERE ROWNUM <= 1