/*For each area that has more than 30 artists, list the male artist, the female artist and the group with the 
most tracks recorded. */
SELECT AREA_NAME, MALE_NAME, FEMALE_NAME, GROUP_NAME FROM(
SELECT AR.NAME AS AREA_NAME, AM.NAME AS MALE_NAME, AF.NAME AS FEMALE_NAME, AG.NAME AS GROUP_NAME, COUNT(DISTINCT ATM.ID_TRACK), COUNT(DISTINCT ATF.ID_TRACK), COUNT(DISTINCT ATG.ID_TRACK),
ROW_NUMBER()OVER (PARTITION BY AR.NAME ORDER BY COUNT(DISTINCT ATM.ID_TRACK)DESC, COUNT(DISTINCT ATF.ID_TRACK) DESC, COUNT(DISTINCT ATG.ID_TRACK)DESC) AS RN
FROM DUMMY_ARTIST AM, DUMMY_AREA AR, DUMMY_ARTIST_TRACK ATM, DUMMY_ARTIST AF, DUMMY_ARTIST_TRACK ATF, DUMMY_ARTIST AG, DUMMY_ARTIST_TRACK ATG
WHERE AM.ID_AREA=AR.ID_AREA AND AM.GENDER='Male' AND AM.ID_ARTIST=ATM.ID_ARTIST AND AF.ID_AREA=AR.ID_AREA AND AF.GENDER='Female' AND AF.ID_ARTIST=ATF.ID_ARTIST
AND AG.TYPE='Group' AND AG.ID_ARTIST=ATG.ID_ARTIST AND AG.ID_AREA=AR.ID_AREA
AND AR.ID_AREA IN (SELECT AR2.ID_AREA
                   FROM DUMMY_AREA AR2, DUMMY_ARTIST A
                   WHERE A.ID_AREA= AR2.ID_AREA
                   GROUP BY AR2.ID_AREA
                   HAVING COUNT(DISTINCT A.ID_ARTIST)>=3)
GROUP BY AR.ID_AREA,AR.NAME, AM.ID_ARTIST, AM.NAME, AF.ID_ARTIST, AF.NAME, AG.ID_ARTIST, AG.NAME)
WHERE RN=1;
