/*For each area that has more than 30 artists, list the male artist, the female artist and the group with the 
most tracks recorded. */

/*SELECT AR.ID_AREA
FROM DUMMY_AREA AR
WHERE (SELECT COUNT(DISTINCT A.ID_ARTIST)
FROM DUMMY_ARTIST A
WHERE A.ID_AREA = AR.ID_AREA) > 3*/

/*(SELECT *
FROM(SELECT A1.ID_ARTIST
FROM DUMMY_ARTIST A1, DUMMY_ARTIST_TRACK AT, DUMMY_AREA A
WHERE A1.ID_ARTIST = AT.ID_ARTIST AND A.ID_AREA = A1.ID_AREA
GROUP BY A1.ID_ARTIST
ORDER BY COUNT(DISTINCT AT.ID_TRACK) DESC)
WHERE ROWNUM = 1)*/

/*
SELECT AR.ID_AREA AS AREA, 
(
  (SELECT *
  FROM(
    SELECT A1.NAME
    FROM DUMMY_ARTIST A1, DUMMY_ARTIST_TRACK AT, DUMMY_AREA AR
    WHERE A1.ID_ARTIST = AT.ID_ARTIST AND AR.ID_AREA = A1.ID_AREA AND AR.GENDER = 'Male'
    GROUP BY A1.ID_ARTIST, A1.NAME
    ORDER BY COUNT(DISTINCT AT.ID_TRACK) DESC
  )
  WHERE ROWNUM = 1)) AS MALE
FROM DUMMY_AREA AR
WHERE (SELECT COUNT(DISTINCT A.ID_ARTIST)
FROM DUMMY_ARTIST A
WHERE A.ID_AREA = AR.ID_AREA) > 3*/

SELECT AR.ID_AREA AS AREA, 
  (SELECT *
   FROM 
        (SELECT A1.ID_ARTIST
         FROM DUMMY_ARTIST A1, DUMMY_ARTIST_TRACK AT
         WHERE A1.ID_ARTIST = AT.ID_ARTIST AND AR.ID_AREA = A1.ID_AREA
         GROUP BY A1.ID_ARTIST
         ORDER BY COUNT(DISTINCT AT.ID_TRACK) DESC)
    WHERE ROWNUM = 1) AS MALE_TRACK
FROM DUMMY_AREA AR;